### ISSUE TITLE
pdfutils OSX vs Ubuntu

### ISSUE THREAD

**Issue by wmbutler** [Gottox/node-pdfutils#14]
The code for pdfutils does not seem to be portable between osx and ubuntu. When I develop locally on OS X and then push to git and then pull to my ubuntu server, I am forced to reinstall pdfutils. I've been using .gitignore but thought you'd like to know about it.

**Comment by srijs** [comment]
That is likely because pdfutils is partly a native addon which needs to be compiled for a specific platform.

**Comment by Gottox** [comment]
Not a bug, there's no way to prevent recompiling. Maybe in magic unicorn land.
