### ISSUE TITLE
Convert Stream to Buffer

### ISSUE THREAD

**Issue by v4l3r10** [Gottox/node-pdfutils#5]
Hi!
it's possible to convert pdf png stream to buffer? 

pdfutils(bufferPDF, function(err, pdf) { 
   var BUFFER =  pdf.asPNG();

})

**Comment by Gottox** [comment]
Not by itself. But they're easy to convert.

See http://stackoverflow.com/questions/14269233/node-js-how-to-read-a-stream-into-a-buffer
