### ISSUE TITLE
Example for streaming the output to an http request?

### ISSUE THREAD

**Issue by wmbutler** [Gottox/node-pdfutils#7]
I'm attempting to use this to split a file into individual pages and then push to couchdb. Is there any chance that you could provide an example in the readme where you make reference to streams?

Ideally I'd like to:

```
for ( var i=0 ; i<doc.length; i++) {
  doc[i].toPDF().toStream()
}
```

Then I'd like to pick up the stream for each file and push make 1 http request per page.

**Comment by wmbutler** [comment]
Getting closer, but just don't know how to redirect this to the http PUT / POST.

```
doc[i].asPDF().pipe(toCouch);
```

**Comment by Gottox** [comment]
See this example: http://nodejs.org/docs/v0.10.0/api/http.html#http_http_request_options_callback

Replace the `write()` and `end()` calls by `doc[i].asPDF().pipe(req);`.

**Comment by wmbutler** [comment]
Thanks
